[package]
name = "default-route"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
local-ip-address = {git = "https://github.com/EstebanBorai/local-ip-address.git"}